import turtle
turtle.ht()
turtle.penup()
turtle.goto(-100,0)
turtle.pendown()
turtle.color("blue")
turtle.begin_fill()
turtle.circle(70)
turtle.penup()
turtle.goto(-100,20)
turtle.pendown()
turtle.circle(50)
turtle.end_fill()
turtle.penup()
turtle.goto(50,20)
turtle.pendown()
turtle.begin_fill()
turtle.color("black")
turtle.circle(50)
turtle.penup()
turtle.goto(50,0)
turtle.circle(70)
turtle.end_fill()

turtle.mainloop()

